/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GoalPeriod = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type MenuCategory = { 'coldDrinks' : null } |
  { 'sandwiches' : null } |
  { 'espressoDrinks' : null } |
  { 'pastries' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : MenuCategory,
  'price' : number,
}
export interface SalesGoal {
  'id' : bigint,
  'period' : GoalPeriod,
  'name' : string,
  'currentProgress' : bigint,
  'targetAmount' : bigint,
  'notes' : string,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : string,
  'title' : string,
  'dueDate' : string,
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type TaskCategory = { 'cleaning' : null } |
  { 'equipment' : null } |
  { 'marketing' : null } |
  { 'staffing' : null } |
  { 'permits' : null };
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface TeamNote {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMenuItem' : ActorMethod<[MenuItem], MenuItem>,
  'createSalesGoal' : ActorMethod<[SalesGoal], SalesGoal>,
  'createTask' : ActorMethod<[Task], Task>,
  'createTeamNote' : ActorMethod<[TeamNote], TeamNote>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteSalesGoal' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTeamNote' : ActorMethod<[bigint], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllSalesGoals' : ActorMethod<[], Array<SalesGoal>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTeamNotes' : ActorMethod<[], Array<TeamNote>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getSalesGoal' : ActorMethod<[bigint], SalesGoal>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTeamNote' : ActorMethod<[bigint], TeamNote>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], MenuItem>,
  'updateSalesGoal' : ActorMethod<[SalesGoal], SalesGoal>,
  'updateTask' : ActorMethod<[Task], Task>,
  'updateTeamNote' : ActorMethod<[TeamNote], TeamNote>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];