/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'attachmentUrl' : IDL.Opt(IDL.Text),
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'attachmentName' : IDL.Opt(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'payable' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'equipment' : IDL.Null,
  'marketing' : IDL.Null,
  'supplies' : IDL.Null,
  'custom' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
  'labor' : IDL.Null,
  'website' : IDL.Null,
  'legal' : IDL.Null,
  'licensing' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'attachmentUrl' : IDL.Opt(IDL.Text),
  'paymentStatus' : PaymentStatus,
  'date' : IDL.Text,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'notes' : IDL.Text,
  'category' : ExpenseCategory,
  'attachmentName' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'parLevel' : IDL.Float64,
  'category' : IDL.Text,
  'unitCost' : IDL.Float64,
});
export const InventoryCountEntry = IDL.Record({
  'actualUsage' : IDL.Float64,
  'purchasesQty' : IDL.Float64,
  'closingQty' : IDL.Float64,
  'openingQty' : IDL.Float64,
  'expectedUsage' : IDL.Float64,
  'waste' : IDL.Float64,
  'ingredientId' : IDL.Nat,
});
export const InventoryCount = IDL.Record({
  'id' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Text,
  'entries' : IDL.Vec(InventoryCountEntry),
  'weekOf' : IDL.Text,
});
export const MenuCategory = IDL.Variant({
  'coldDrinks' : IDL.Null,
  'sandwiches' : IDL.Null,
  'espressoDrinks' : IDL.Null,
  'pastries' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : MenuCategory,
  'price' : IDL.Float64,
});
export const RecipeIngredient = IDL.Record({
  'quantityUsed' : IDL.Float64,
  'ingredientId' : IDL.Nat,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'notes' : IDL.Text,
  'menuItemId' : IDL.Nat,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'date' : IDL.Text,
  'createdBy' : IDL.Text,
  'notes' : IDL.Text,
  'totalRevenue' : IDL.Float64,
});
export const GoalPeriod = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const SalesGoal = IDL.Record({
  'id' : IDL.Nat,
  'period' : GoalPeriod,
  'name' : IDL.Text,
  'currentProgress' : IDL.Nat,
  'targetAmount' : IDL.Nat,
  'notes' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'equipment' : IDL.Null,
  'marketing' : IDL.Null,
  'staffing' : IDL.Null,
  'permits' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'category' : TaskCategory,
  'priority' : TaskPriority,
});
export const TeamNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ChatMessage],
      [],
    ),
  'createExpense' : IDL.Func([Expense], [Expense], []),
  'createIngredient' : IDL.Func([Ingredient], [Ingredient], []),
  'createInventoryCount' : IDL.Func([InventoryCount], [InventoryCount], []),
  'createMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
  'createRecipe' : IDL.Func([Recipe], [Recipe], []),
  'createRevenueEntry' : IDL.Func([RevenueEntry], [RevenueEntry], []),
  'createSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
  'createTask' : IDL.Func([Task], [Task], []),
  'createTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
  'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryCount' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
  'deleteRevenueEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSalesGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamNote' : IDL.Func([IDL.Nat], [], []),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllInventoryCounts' : IDL.Func([], [IDL.Vec(InventoryCount)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getAllSalesGoals' : IDL.Func([], [IDL.Vec(SalesGoal)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTeamNotes' : IDL.Func([], [IDL.Vec(TeamNote)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
  'getExpensesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getIngredient' : IDL.Func([IDL.Nat], [Ingredient], ['query']),
  'getInventoryCount' : IDL.Func([IDL.Nat], [InventoryCount], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getRecipe' : IDL.Func([IDL.Nat], [Recipe], ['query']),
  'getRecipeByMenuItem' : IDL.Func([IDL.Nat], [Recipe], ['query']),
  'getRevenueByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(RevenueEntry)],
      ['query'],
    ),
  'getRevenueEntry' : IDL.Func([IDL.Nat], [RevenueEntry], ['query']),
  'getSalesGoal' : IDL.Func([IDL.Nat], [SalesGoal], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTeamNote' : IDL.Func([IDL.Nat], [TeamNote], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func([Expense], [Expense], []),
  'updateIngredient' : IDL.Func([Ingredient], [Ingredient], []),
  'updateMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
  'updateRecipe' : IDL.Func([Recipe], [Recipe], []),
  'updateRevenueEntry' : IDL.Func([RevenueEntry], [RevenueEntry], []),
  'updateSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
  'updateTask' : IDL.Func([Task], [Task], []),
  'updateTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'attachmentName' : IDL.Opt(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'payable' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'equipment' : IDL.Null,
    'marketing' : IDL.Null,
    'supplies' : IDL.Null,
    'custom' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
    'labor' : IDL.Null,
    'website' : IDL.Null,
    'legal' : IDL.Null,
    'licensing' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'paymentStatus' : PaymentStatus,
    'date' : IDL.Text,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'notes' : IDL.Text,
    'category' : ExpenseCategory,
    'attachmentName' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'parLevel' : IDL.Float64,
    'category' : IDL.Text,
    'unitCost' : IDL.Float64,
  });
  const InventoryCountEntry = IDL.Record({
    'actualUsage' : IDL.Float64,
    'purchasesQty' : IDL.Float64,
    'closingQty' : IDL.Float64,
    'openingQty' : IDL.Float64,
    'expectedUsage' : IDL.Float64,
    'waste' : IDL.Float64,
    'ingredientId' : IDL.Nat,
  });
  const InventoryCount = IDL.Record({
    'id' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Text,
    'entries' : IDL.Vec(InventoryCountEntry),
    'weekOf' : IDL.Text,
  });
  const MenuCategory = IDL.Variant({
    'coldDrinks' : IDL.Null,
    'sandwiches' : IDL.Null,
    'espressoDrinks' : IDL.Null,
    'pastries' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : MenuCategory,
    'price' : IDL.Float64,
  });
  const RecipeIngredient = IDL.Record({
    'quantityUsed' : IDL.Float64,
    'ingredientId' : IDL.Nat,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'notes' : IDL.Text,
    'menuItemId' : IDL.Nat,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'date' : IDL.Text,
    'createdBy' : IDL.Text,
    'notes' : IDL.Text,
    'totalRevenue' : IDL.Float64,
  });
  const GoalPeriod = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const SalesGoal = IDL.Record({
    'id' : IDL.Nat,
    'period' : GoalPeriod,
    'name' : IDL.Text,
    'currentProgress' : IDL.Nat,
    'targetAmount' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'equipment' : IDL.Null,
    'marketing' : IDL.Null,
    'staffing' : IDL.Null,
    'permits' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  const TeamNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ChatMessage],
        [],
      ),
    'createExpense' : IDL.Func([Expense], [Expense], []),
    'createIngredient' : IDL.Func([Ingredient], [Ingredient], []),
    'createInventoryCount' : IDL.Func([InventoryCount], [InventoryCount], []),
    'createMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
    'createRecipe' : IDL.Func([Recipe], [Recipe], []),
    'createRevenueEntry' : IDL.Func([RevenueEntry], [RevenueEntry], []),
    'createSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
    'createTask' : IDL.Func([Task], [Task], []),
    'createTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
    'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryCount' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
    'deleteRevenueEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSalesGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamNote' : IDL.Func([IDL.Nat], [], []),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllInventoryCounts' : IDL.Func(
        [],
        [IDL.Vec(InventoryCount)],
        ['query'],
      ),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getAllSalesGoals' : IDL.Func([], [IDL.Vec(SalesGoal)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTeamNotes' : IDL.Func([], [IDL.Vec(TeamNote)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
    'getExpensesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getIngredient' : IDL.Func([IDL.Nat], [Ingredient], ['query']),
    'getInventoryCount' : IDL.Func([IDL.Nat], [InventoryCount], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getRecipe' : IDL.Func([IDL.Nat], [Recipe], ['query']),
    'getRecipeByMenuItem' : IDL.Func([IDL.Nat], [Recipe], ['query']),
    'getRevenueByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(RevenueEntry)],
        ['query'],
      ),
    'getRevenueEntry' : IDL.Func([IDL.Nat], [RevenueEntry], ['query']),
    'getSalesGoal' : IDL.Func([IDL.Nat], [SalesGoal], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTeamNote' : IDL.Func([IDL.Nat], [TeamNote], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func([Expense], [Expense], []),
    'updateIngredient' : IDL.Func([Ingredient], [Ingredient], []),
    'updateMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
    'updateRecipe' : IDL.Func([Recipe], [Recipe], []),
    'updateRevenueEntry' : IDL.Func([RevenueEntry], [RevenueEntry], []),
    'updateSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
    'updateTask' : IDL.Func([Task], [Task], []),
    'updateTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
  });
};

export const init = ({ IDL }) => { return []; };