/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuCategory = IDL.Variant({
  'coldDrinks' : IDL.Null,
  'sandwiches' : IDL.Null,
  'espressoDrinks' : IDL.Null,
  'pastries' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : MenuCategory,
  'price' : IDL.Float64,
});
export const GoalPeriod = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const SalesGoal = IDL.Record({
  'id' : IDL.Nat,
  'period' : GoalPeriod,
  'name' : IDL.Text,
  'currentProgress' : IDL.Nat,
  'targetAmount' : IDL.Nat,
  'notes' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'equipment' : IDL.Null,
  'marketing' : IDL.Null,
  'staffing' : IDL.Null,
  'permits' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'category' : TaskCategory,
  'priority' : TaskPriority,
});
export const TeamNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
  'createSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
  'createTask' : IDL.Func([Task], [Task], []),
  'createTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteSalesGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamNote' : IDL.Func([IDL.Nat], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllSalesGoals' : IDL.Func([], [IDL.Vec(SalesGoal)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTeamNotes' : IDL.Func([], [IDL.Vec(TeamNote)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getSalesGoal' : IDL.Func([IDL.Nat], [SalesGoal], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTeamNote' : IDL.Func([IDL.Nat], [TeamNote], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
  'updateSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
  'updateTask' : IDL.Func([Task], [Task], []),
  'updateTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuCategory = IDL.Variant({
    'coldDrinks' : IDL.Null,
    'sandwiches' : IDL.Null,
    'espressoDrinks' : IDL.Null,
    'pastries' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : MenuCategory,
    'price' : IDL.Float64,
  });
  const GoalPeriod = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const SalesGoal = IDL.Record({
    'id' : IDL.Nat,
    'period' : GoalPeriod,
    'name' : IDL.Text,
    'currentProgress' : IDL.Nat,
    'targetAmount' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'equipment' : IDL.Null,
    'marketing' : IDL.Null,
    'staffing' : IDL.Null,
    'permits' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  const TeamNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
    'createSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
    'createTask' : IDL.Func([Task], [Task], []),
    'createTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteSalesGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamNote' : IDL.Func([IDL.Nat], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllSalesGoals' : IDL.Func([], [IDL.Vec(SalesGoal)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTeamNotes' : IDL.Func([], [IDL.Vec(TeamNote)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getSalesGoal' : IDL.Func([IDL.Nat], [SalesGoal], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTeamNote' : IDL.Func([IDL.Nat], [TeamNote], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
    'updateSalesGoal' : IDL.Func([SalesGoal], [SalesGoal], []),
    'updateTask' : IDL.Func([Task], [Task], []),
    'updateTeamNote' : IDL.Func([TeamNote], [TeamNote], []),
  });
};

export const init = ({ IDL }) => { return []; };