/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'attachmentUrl' : [] | [string],
  'body' : string,
  'tags' : Array<string>,
  'authorName' : string,
  'timestamp' : bigint,
  'attachmentName' : [] | [string],
}
export interface Expense {
  'id' : bigint,
  'attachmentUrl' : [] | [string],
  'paymentStatus' : PaymentStatus,
  'date' : string,
  'createdBy' : string,
  'description' : string,
  'notes' : string,
  'category' : ExpenseCategory,
  'attachmentName' : [] | [string],
  'amount' : number,
}
export type ExpenseCategory = { 'cleaning' : null } |
  { 'equipment' : null } |
  { 'marketing' : null } |
  { 'supplies' : null } |
  { 'custom' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'labor' : null } |
  { 'website' : null } |
  { 'legal' : null } |
  { 'licensing' : null };
export type GoalPeriod = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface Ingredient {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'parLevel' : number,
  'category' : string,
  'unitCost' : number,
}
export interface InventoryCount {
  'id' : bigint,
  'submittedAt' : bigint,
  'submittedBy' : string,
  'entries' : Array<InventoryCountEntry>,
  'weekOf' : string,
}
export interface InventoryCountEntry {
  'actualUsage' : number,
  'purchasesQty' : number,
  'closingQty' : number,
  'openingQty' : number,
  'expectedUsage' : number,
  'waste' : number,
  'ingredientId' : bigint,
}
export type MenuCategory = { 'coldDrinks' : null } |
  { 'sandwiches' : null } |
  { 'espressoDrinks' : null } |
  { 'pastries' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : MenuCategory,
  'price' : number,
}
export type PaymentStatus = { 'paid' : null } |
  { 'payable' : null };
export interface Recipe {
  'id' : bigint,
  'notes' : string,
  'menuItemId' : bigint,
  'ingredients' : Array<RecipeIngredient>,
}
export interface RecipeIngredient {
  'quantityUsed' : number,
  'ingredientId' : bigint,
}
export interface RevenueEntry {
  'id' : bigint,
  'source' : string,
  'date' : string,
  'createdBy' : string,
  'notes' : string,
  'totalRevenue' : number,
}
export interface SalesGoal {
  'id' : bigint,
  'period' : GoalPeriod,
  'name' : string,
  'currentProgress' : bigint,
  'targetAmount' : bigint,
  'notes' : string,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : string,
  'title' : string,
  'dueDate' : string,
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type TaskCategory = { 'cleaning' : null } |
  { 'equipment' : null } |
  { 'marketing' : null } |
  { 'staffing' : null } |
  { 'permits' : null };
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface TeamNote {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatMessage' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    ChatMessage
  >,
  'createExpense' : ActorMethod<[Expense], Expense>,
  'createIngredient' : ActorMethod<[Ingredient], Ingredient>,
  'createInventoryCount' : ActorMethod<[InventoryCount], InventoryCount>,
  'createMenuItem' : ActorMethod<[MenuItem], MenuItem>,
  'createRecipe' : ActorMethod<[Recipe], Recipe>,
  'createRevenueEntry' : ActorMethod<[RevenueEntry], RevenueEntry>,
  'createSalesGoal' : ActorMethod<[SalesGoal], SalesGoal>,
  'createTask' : ActorMethod<[Task], Task>,
  'createTeamNote' : ActorMethod<[TeamNote], TeamNote>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteIngredient' : ActorMethod<[bigint], undefined>,
  'deleteInventoryCount' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteRecipe' : ActorMethod<[bigint], undefined>,
  'deleteRevenueEntry' : ActorMethod<[bigint], undefined>,
  'deleteSalesGoal' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTeamNote' : ActorMethod<[bigint], undefined>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getAllInventoryCounts' : ActorMethod<[], Array<InventoryCount>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getAllRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getAllSalesGoals' : ActorMethod<[], Array<SalesGoal>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTeamNotes' : ActorMethod<[], Array<TeamNote>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[bigint], Expense>,
  'getExpensesByDateRange' : ActorMethod<[string, string], Array<Expense>>,
  'getIngredient' : ActorMethod<[bigint], Ingredient>,
  'getInventoryCount' : ActorMethod<[bigint], InventoryCount>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getRecipe' : ActorMethod<[bigint], Recipe>,
  'getRecipeByMenuItem' : ActorMethod<[bigint], Recipe>,
  'getRevenueByDateRange' : ActorMethod<[string, string], Array<RevenueEntry>>,
  'getRevenueEntry' : ActorMethod<[bigint], RevenueEntry>,
  'getSalesGoal' : ActorMethod<[bigint], SalesGoal>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTeamNote' : ActorMethod<[bigint], TeamNote>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpense' : ActorMethod<[Expense], Expense>,
  'updateIngredient' : ActorMethod<[Ingredient], Ingredient>,
  'updateMenuItem' : ActorMethod<[MenuItem], MenuItem>,
  'updateRecipe' : ActorMethod<[Recipe], Recipe>,
  'updateRevenueEntry' : ActorMethod<[RevenueEntry], RevenueEntry>,
  'updateSalesGoal' : ActorMethod<[SalesGoal], SalesGoal>,
  'updateTask' : ActorMethod<[Task], Task>,
  'updateTeamNote' : ActorMethod<[TeamNote], TeamNote>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];